//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kt_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string BillingDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
